### ISSUE TITLE
[Bug]: mumble 1.4 plugins cannot be installed

### ISSUE THREAD

**Issue by hbeni** [snapcrafters/.github#12]
### What happened?

When trying to install the [fgcom-mumble](https://github.com/hbeni/fgcom-mumble) plugin, the sandboxing somehow prevents loading the Plugin shared object.
Mumble presents a (misleading) error about wrong plugin api, but the rootcause seems to be a problem with loading the shared object.

Even manually installing the (verified working) plugin.so by copying it into the plugins folder does not work.

### What should have happened?

Plugins should also work with the snap version.

### Details
- https://forum.flightgear.org/viewtopic.php?p=409953#p409953
- https://github.com/hbeni/fgcom-mumble

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting, but this is not the right repository.

Please re-file this here: https://github.com/snapcrafters/mumble/issues

**Comment by hbeni** [comment]
Oh sorry
Opened https://github.com/snapcrafters/mumble/issues/23
